TRUNCATE `Android_Channel`;
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('1','000054','huawei');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('2','000016','lenovo');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('3','000020','oppo');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('4','000084','gionee');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('5','000014','meizu');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('6','000368','vivo');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('7','000066','mi');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('8','160280','coolpad');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('9','160136','tencent');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('10','000255','aligames');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('11','110000','baidu');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('12','000023','qihu');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('13','999999','test_anysdk');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('14','160086','pengyouwan');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('15','000003','downjoy');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('16','000247','muzhiwan');
INSERT INTO `Android_Channel` (`id`,`channel_id`,`channel_name`) VALUES ('17','160198','x7sy');
