TRUNCATE `Loading_desc`;
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('1','290001','宫殿位于地图中心，占领宫殿的联盟才有权利选举国王！');
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('2','290002','提高出征部队中武将的带兵数和士兵的属性能显著提高部队战斗能力。');
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('3','290003','4件同品质的“翡翠”能合成1件高品质翡翠，其他材料也是如此。');
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('4','290004','采集资源时要小心，若被敌人击败，部队采集的资源是会被掠夺的！');
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('5','290005','将武将驻守到建造中可以提高建筑的效果！');
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('6','290006','战斗集结时，所有集结玩家享有集结发起者的科技、天赋等增益效果。（发起者以外的增益效果无效）');
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('7','290007','防御型的步兵可以承受大量伤害，他们在战斗中必不可少！');
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('8','290008','弓兵和骑兵有着强大的攻击能力，但防御能力较差。');
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('9','290009','车兵在攻城战中的作用无可替代。');
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('10','290010','粮田产量越高，可拥有的士兵数量越多。');
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('11','290011','酒馆等级越高，可招募的武将数量越多。');
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('12','290012','有武将驻守城墙时，可使防守城池的士兵更强力。');
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('13','290013','军团有更多的副将才能带领更多的士兵出征。');
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('14','290014','装备升星需要足够的装备材料和1件同品质的其他装备。');
INSERT INTO `Loading_desc` (`id`,`tips`,`desc`) VALUES ('15','290015','军团行军时，可以消耗体力直达目的地，距离越远消耗体力越多。');
