<style>
#dataTable1{
	background:white;
}
#dataTable1 th{
	width:150px;
}
#dataTable1 td{
	/*word-wrap:break-word;
	word-break:break-all;*/
}
#detailInfoModal .form-control{
	word-wrap:break-word;
	word-break:break-all;
	height:auto;
}

.Wdate{
	height:30px;
	width:250px;
}
#dataTable1_filter{
	display:none;
}
</style>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">活动列表</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>

<div class="row" id="orderFilterForm">
	<div class="col-lg-12">
		<div class="panel panel-danger">
			<div class="panel-heading"> 筛选 </div>
			<div class="panel-body">
				<form method="POST">
					<div class="form-group">
						<label>类型</label>
						<select class="form-control" id="activity_id" style="width:250px;" defaultVal="">
							<option value="">所有</option>
							<option value="1017"><?php echo $activity[1017]['name_dec']?></option>
							<option value="1018"><?php echo $activity[1018]['name_dec']?></option>
							<option value="1019"><?php echo $activity[1019]['name_dec']?></option>
							<option value="1022"><?php echo $activity[1022]['name_dec']?></option>
							<option value="1023"><?php echo $activity[1023]['name_dec']?></option>
							<option value="1026"><?php echo $activity[1026]['name_dec']?></option>
							<option value="1027"><?php echo $activity[1027]['name_dec']?></option>
							<option value="1028"><?php echo $activity[1028]['name_dec']?></option>
						</select>
					</div>
					<div class="col-lg-2">
						<button onclick="findSubmit()" type="button" class="btn btn-primary btn-lg">查找</button>
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- /.col-lg-12 -->
</div>


<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 活动列表 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>编号</th>
						<th>名称</th>
						<th>类型</th>
						<th>开始时间</th>
						<th>结束时间</th>
						<th>创建时间</th>
						<th>状态</th>
						<th>操作</th>
					</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<?php echo \Phalcon\Tag::javascriptInclude("js/My97DatePicker/WdatePicker.js"); ?>
<script>
var gTable1;
$(document).ready(function(){
    gTable1 = $('#dataTable1').DataTable({
		"autoWidth": false,
		"processing": true,
        "serverSide": true,
        "ajax": {
            "url": "/admin/ajaxActivityShow",
			"type": "POST",
            "data": function ( d ) {
				d.activity_id = $("#activity_id").val();
            }
        },
		"columns": [
            { "data": "id" },
            { "data": "activity_name" },
            { "data": "activity_id" },
			{ "data": "show_time" },
			{ "data": "end_time" },
			{ "data": "create_time" },
			{ "data": "status" },
			{ "data": "operation" },
        ],
		"pageLength": 25
	});
});


function findSubmit(){
	gTable1.draw();
}

function changeActStatus(id, status){
	commonSend('ajaxActivityChangeStatus', {actConfigId:id, status:status}, '', false, findSubmit);
}

function editAct(actId, actConfigId){
	var url = '';
	switch(actId){
		case 1017:
			url = 'addActivityLogin';
		break;
		case 1018:
			url = 'addActivityCharge';
		break;
		case 1019:
			url = 'addActivityNpcDrop';
		break;
		case 1022:
			url = 'addActivityConsume';
		break;
		case 1023:
			url = 'addActivityWheel';
		break;
		case 1026:
			url = 'addActivityExchange';
		break;
		case 1027:
			url = 'addActivityPanicBuy';
		break;
		case 1028:
			url = 'addActivitySacrifice';
		break;
	}
	location.href = '/admin/'+url+'/'+actConfigId;
}
</script>