<style>
.Wdate{
	height:30px;
	width:250px;
}
</style>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">客户端版本号</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="form-group">
					<label>当前game_version值</label>
					<input class="form-control" placeholder="输入ip，英文逗号分隔" id="gameVersion" value="<?=@$currentGameVersion?>" />
				</div>
				<button type="button" class="btn btn-primary" onclick="P.alterGameVersion()">保存</button>
			</div>
		</div>
	</div>
</div>

<script>
	var P = {};
	P.alterGameVersion = function (){
		var gameVersion = $.trim($('#gameVersion').val());
		$.post('/admin/ajaxAlterGameVersion', {"gameVersion":gameVersion}, function(o){
			alertOk('更改成功', flushPage);
		})
	};
	function flushPage(){
		location.reload();
	}
</script>