<style>
</style>
<div class="row">
    <div class="col-lg-12">
    <h1 class="page-header">阵营聊天-camp_id=<?=$campId?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<span id="notice"></span>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading"> 阵营聊天-camp_id=<?=$campId?> </div>
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="chatTable">
                    <thead>
                    <tr>
                        <th>服务器id</th>
                        <th>玩家id</th>
                        <th>昵称</th>
                        <th>联盟短名称</th>
                        <th>内容</th>
                        <th>时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($campMsg as $k=>$v):
                        ?>
                        <tr>
                            <td><?=@$v['server_id']?></td>
                            <td><?=$v['player_id']?></td>
                            <td><?=$v['nick']?></td>
                            <td><?=$v['guild_short_name']?></td>
                            <td><?=$v['content']?></td>
                            <td><?=$v['date']?></td>
                            <td>
                            <a class="btn btn-danger" href="javascript:;" onclick="delSingle(<?=$k?>);">删除</a>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<button type="button" class="btn btn-primary" onclick="flushAll();" style="margin:20px auto 0;">全清camp_id=<?=$campId?></button>

<script>
function flushAll(){
    if(confirm('全部清除阵营camp_id=<?=$campId?>聊天?')) {
        $.post('/admin/ajaxFlushAllCampChat', {'camp_id':<?=$campId?>}, function(o){
            location.reload();
        });
    }
}
function delSingle(id){
    if(confirm('删除当前条目?')) {
        $.post('/admin/delSingleCampChat', {"id":id, 'camp_id':<?=$campId?>}, function(o){
            location.reload();
        });
    }
}
$(document).ready(function(){
    $('#chatTable').DataTable({
        "pageLength": 100,
        "aaSorting": [[ 4, "desc" ]]
    });
});
</script>