<style>
#dataTable1{
	background:white;
}
#dataTable1 th{
	width:150px;
}
#dataTable1 td{
	/*word-wrap:break-word;
	word-break:break-all;*/
}
#detailInfoModal .form-control{
	word-wrap:break-word;
	word-break:break-all;
	height:auto;
}

.Wdate{
	height:30px;
	width:250px;
}
</style>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">查看激活码礼包</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 礼包列表 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>编号</th>
						<th>名称</th>
						<th>道具代码</th>
						<th>备注</th>
						<th>创建时间</th>
						<th>操作</th>
					</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<script>
var gTable1;
$(document).ready(function(){
    gTable1 = $('#dataTable1').DataTable({
		"autoWidth": false,
		"processing": true,
        "serverSide": true,
        "ajax": {
            "url": "/admin/ajaxCdkDropShow",
			"type": "POST",
            "data": function ( d ) {
            }
        },
		"columns": [
            { "data": "id" },
            { "data": "name" },
            { "data": "drop" },
            { "data": "memo" },
            { "data": "create_time" },
			{ "data": "operation", "orderable": false },
        ],
		"pageLength": 25
	});
	$("#dataTable1_filter input[type=search]").attr('title', '（）中内容不支持搜索');
});


function findSubmit(){
	gTable1.draw();
}


function changeStatus(id){
	if(confirm('是否删除礼包？')){
		send_request_json('/admin/ajaxCdkDropDelete', 
			{id: id}, 
			function(ret){
			if(ret.err == 'ok'){
				alertOk('成功', function(){
					location.reload();
				});
			}else{
				alertErr(ret.err);
			}
		});
	}
}
</script>