<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">配置激活码礼包</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 激活码礼包 </div>
			<div class="panel-body">
				<form method="POST">
					<div class="form-group">
						<label>礼包名称</label>
						<input class="form-control" rows="3" placeholder="" id="cdkDropName" />
					</div>
					<div class="form-group">
						<label>备注</label>
						<textarea class="form-control" rows="3" placeholder="" id="cdkDropMemo" disabled="true"></textarea>
					</div>
					<div class="form-group">
						<label>道具</label>
						<textarea class="form-control" rows="3" placeholder="输入道具代码（type1,id1,num1;type2,id2,num2;）" id="cdkDrop"></textarea>
					</div>
				  <button type="button" class="btn btn-primary" onclick="cdkDropGenerateSubmit()">新增</button>
				</form>
			</div>
		</div>
	</div>
	<!-- /.col-lg-12 -->
</div>

<?php $this->partial("shared/dropCreate", array('dropInputId' => 'cdkDrop', 'memoInputId'=>'cdkDropMemo')); ?>

<script>
function cdkDropGenerateSubmit(){
	send_request_json('/admin/ajaxCdkDropGenerate', 
	{
		cdkDropName: $("#cdkDropName").val(),
		cdkDropMemo: $("#cdkDropMemo").val(),
		cdkDrop: $("#cdkDrop").val()
	}, 
	function(ret){
		if(ret.err == 'ok'){
			alertOk('完成', function(){
				location.reload();
			});
		}else{
			alertErr(ret.err);
		}
	});
}

</script>