<style>
#dataTable1{
	background:white;
}
#dataTable1 th{
	width:150px;
}
#dataTable1 td{
	/*word-wrap:break-word;
	word-break:break-all;*/
}
#detailInfoModal .form-control{
	word-wrap:break-word;
	word-break:break-all;
	height:auto;
}

.Wdate{
	height:30px;
	width:250px;
}
#dataTable1_filter{
	display:none;
}
</style>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">查看激活码</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>

<div class="row" id="orderFilterForm">
	<div class="col-lg-12">
		<div class="panel panel-danger">
			<div class="panel-heading"> 筛选 </div>
			<div class="panel-body">
				<form method="POST">
					<div class="form-group">
						<label>激活码</label>
						<input id="cdk" placeholder="" class="form-control" defaultVal=""style="width:250px;" />
					</div>
					<div class="form-group">
						<label>语言版本</label>
						<select class="form-control" id="cdkLang" style="width:250px;" defaultVal="-1">
							<option value="-1">所有</option>
						<?php foreach($lang as $_k => $_lang){?>
							<option value="<?php echo $_k?>"><?php echo $_lang?></option>
						<?php }?>
						</select>
					</div>
					<div class="form-group">
						<label>渠道</label>
						<select class="form-control" id="cdkChannel" style="width:250px;" defaultVal="-1">
							<option value="-1">所有</option>
						<?php foreach($channel as $_k => $_lang){?>
							<option value="<?php echo $_k?>"><?php echo $_lang?></option>
						<?php }?>
						</select>
					</div>
					<div class="form-group">
						<label>类型</label>
						<select class="form-control" id="cdkType" style="width:250px;" defaultVal="-1">
							<option value="-1">所有</option>
						<?php foreach($type as $_k => $_lang){?>
							<option value="<?php echo $_k?>"><?php echo $_lang?></option>
						<?php }?>
						</select>
					</div>
					<div class="form-group">
						<label>有效时间</label>
						<div>
							<input id="beginTime" placeholder="" class="form-control Wdate" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})" defaultVal="" style="float:left"/>
							<span style="float:left;padding:5px;">~</span>
							<input id="endTime" placeholder="" class="form-control Wdate" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})" defaultVal="" style="float:left"/>
							<div class="clear"></div>
						</div>
					</div>
					<div class="form-group">
						<label>创建时间</label>
						<div>
							<input id="createBeginTime" placeholder="" class="form-control Wdate" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})" defaultVal="" style="float:left"/>
							<span style="float:left;padding:5px;">~</span>
							<input id="createEndTime" placeholder="" class="form-control Wdate" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})" defaultVal="" style="float:left"/>
							<div class="clear"></div>
						</div>
					</div>
					<div class="form-group">
						<label>兑换码前缀</label>
						<input class="form-control" rows="3" placeholder="" id="cdkPre" maxlength="2" onKeyUp="value=value.replace(/[^a-zA-Z0-9]/g,'')" style="width:250px;" />
					</div>
					<div class="form-group">
						<label>备注</label>
						<textarea class="form-control" rows="3" placeholder="" id="cdkMemo"></textarea>
					</div>
					<div class="col-lg-2">
						<button onclick="findSubmit()" type="button" class="btn btn-primary btn-lg">查找</button>
					</div>
					<div class="col-lg-2">
						<button onclick="cdkGenerateExport()" type="button" class="btn btn-danger btn-lg">导出</button>
					</div>
					<div class="col-lg-2">
						<button onclick="resetForm()" type="button" class="btn btn-warning btn-lg">清空</button>
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- /.col-lg-12 -->
</div>


<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> cdk列表 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>编号</th>
						<th>激活码</th>
						<th>类型</th>
						<th>语言</th>
						<th>渠道</th>
						<th>drop</th>
						<th>使用人数</th>
						<th>备注</th>
						<th>状态</th>
						<th>有效开始时间</th>
						<th>有效结束时间</th>
						<th>创建时间</th>
						<th>更新时间</th>
					</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<?php echo \Phalcon\Tag::javascriptInclude("js/My97DatePicker/WdatePicker.js"); ?>
<script>
var gTable1;
$(document).ready(function(){
    gTable1 = $('#dataTable1').DataTable({
		"autoWidth": false,
		"processing": true,
        "serverSide": true,
        "ajax": {
            "url": "/admin/ajaxCdkSearch",
			"type": "POST",
            "data": function ( d ) {
				d.cdk = $("#cdk").val();
				d.cdkLang = $("#cdkLang").val();
				d.cdkChannel = $("#cdkChannel").val();
				d.cdkType = $("#cdkType").val();
				d.beginTime = $("#beginTime").val();
				d.endTime = $("#endTime").val();
				d.createBeginTime = $("#createBeginTime").val();
				d.createEndTime = $("#createEndTime").val();
				d.cdkPre = $("#cdkPre").val();
				d.cdkMemo = $("#cdkMemo").val();
            }
        },
		"columns": [
            { "data": "id" },
            { "data": "cdk" },
            { "data": "type" },
			{ "data": "lang" },
			{ "data": "channel" },
			{ "data": "drop" },
			{ "data": "count" },
            { "data": "memo" },
			{ "data": "status" },
            { "data": "begin_time" },
			{ "data": "end_time" },
			{ "data": "create_time" },
			{ "data": "update_time" },
        ],
		"pageLength": 25
	});
	$("#dataTable1_filter input[type=search]").attr('title', '（）中内容不支持搜索');
});

function resetForm(){
	$("#orderFilterForm").find('input,select,textarea').each(function(){
		$(this).val($(this).attr('defaultVal'));
	});
}


function findSubmit(){
	gTable1.draw();
}

function cdkGenerateExport(){
	var str = $.param({
		cdk : $("#cdk").val(),
		cdkLang : $("#cdkLang").val(),
		cdkChannel : $("#cdkChannel").val(),
		cdkType : $("#cdkType").val(),
		beginTime : $("#beginTime").val(),
		endTime : $("#endTime").val(),
		createBeginTime : $("#createBeginTime").val(),
		createEndTime : $("#createEndTime").val(),
		cdkPre : $("#cdkPre").val(),
		cdkMemo : $("#cdkMemo").val(),
		export : 1
	});
	window.open('/admin/ajaxCdkSearch?'+str);
}

</script>