<style>
#dataTable1{
	background:white;
}
#dataTable1 th{
	width:150px;
}
#dataTable1 td{
	/*word-wrap:break-word;
	word-break:break-all;*/
}
#detailInfoModal .form-control{
	word-wrap:break-word;
	word-break:break-all;
	height:auto;
}

.Wdate{
	height:30px;
	width:250px;
}
#dataTable1_filter{
	display:none;
}
</style>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">单届详情</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>

<div class="row" id="orderFilterForm">
	<div class="col-lg-12">
		<div class="panel panel-danger">
			<div class="panel-heading"> 筛选 </div>
			<div class="panel-body">
				<form method="POST">
					<div class="form-group">
						<label>届数</label>
						<input class="form-control" id="cbRoundId" style="width:250px;" value="<?php echo @$_REQUEST['roundId']?>" defaultVal="">
					</div>
					<div class="form-group">
						<label>城市</label>
						<select class="form-control" id="cbCityId" style="width:250px;"  autocomplete="off">
							<option value="0">所有</option>
							<?php foreach($cities as $_id=>$_city){?>
								<option value="<?php echo $_id?>" <?php echo (@$_REQUEST['cityId']==$_id?' selected="selected"':'') ?>><?php echo $_city['desc']?></option>
							<?php }?>
						</select>
					</div>
					<div class="col-lg-2">
						<button onclick="findSubmit()" type="button" class="btn btn-primary btn-lg">查找</button>
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- /.col-lg-12 -->
</div>


<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 列表 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>id</th>
						<th>届数</th>
						<th>城市</th>
						<th>所属</th>
						<th>状态</th>
						<th>胜利方</th>
						<th>城门战开始</th>
						<th>内城战开始</th>
						<th>内攻方</th>
						<th>内防方</th>
						<th>内攻分</th>
						<th>内防分</th>
						<th>分数统计时间</th>
						<th>门(魏)</th>
						<th>门(蜀)</th>
						<th>门(吴)</th>
						<th>杀(魏)</th>
						<th>杀(蜀)</th>
						<th>杀(吴)</th>
						<th>报名数(魏)</th>
						<th>报名数(蜀)</th>
						<th>报名数(吴)</th>
						<th>城门战持续秒</th>
					</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<?php echo \Phalcon\Tag::javascriptInclude("js/My97DatePicker/WdatePicker.js"); ?>
<script>
var gTable1;
$(document).ready(function(){
    gTable1 = $('#dataTable1').DataTable({
		"autoWidth": false,
		"processing": true,
        "serverSide": true,
        "ajax": {
            "url": "/admin/ajaxCityBattle",
			"type": "POST",
            "data": function ( d ) {
				d.roundId = $("#cbRoundId").val();
				d.cityId = $("#cbCityId").val();
            }
        },
		"columns": [
            { "data": "id" },
			{ "data": "round_id" },
			{ "data": "city_id" },
			{ "data": "camp_id" },
			{ "data": "status" },
			{ "data": "win_camp" },
			{ "data": "real_start_time" },
			{ "data": "melee_time" },
			{ "data": "attack_camp" },
			{ "data": "defend_camp" },
			{ "data": "attack_score" },
			{ "data": "defend_score" },
			{ "data": "score_time" },
			{ "data": "door1" },
			{ "data": "door2" },
			{ "data": "door3" },
			{ "data": "camp_1_kill" },
			{ "data": "camp_2_kill" },
			{ "data": "camp_3_kill" },
			{ "data": "sign_num_wei" },
			{ "data": "sign_num_shu" },
			{ "data": "sign_num_wu" },
			{ "data": "operation" },
        ],
		"pageLength": 25
	});
});


function findSubmit(){
	gTable1.draw();
}
</script>