<style>
#dataTable1{
	background:white;
}
#dataTable1 th{
	width:150px;
}
#dataTable1 td{
	/*word-wrap:break-word;
	word-break:break-all;*/
}
#detailInfoModal .form-control{
	word-wrap:break-word;
	word-break:break-all;
	height:auto;
}

.Wdate{
	height:30px;
	width:250px;
}
#dataTable1_filter{
	display:none;
}
</style>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">阵营详情</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>

<div class="row" id="orderFilterForm">
	<div class="col-lg-12">
		<div class="panel panel-danger">
			<div class="panel-heading"> 筛选 </div>
			<div class="panel-body">
				<form method="POST">
					<div class="form-group">
						<label>届数</label>
						<input class="form-control" id="cbRoundId" style="width:250px;" value="<?php echo @$_REQUEST['roundId']?>" defaultVal="">
					</div>
					<div class="form-group">
						<label>战斗编号</label>
						<input class="form-control" id="cbBattleId" style="width:250px;" value="<?php echo @$_REQUEST['battleId']?>" defaultVal="">
					</div>
					<div class="form-group">
						<label>阵营</label>
						<select class="form-control" id="cbCampId" style="width:250px;"  autocomplete="off">
							<option value="0">所有</option>
							<?php foreach($camps as $_id=>$_camp){?>
								<option value="<?php echo $_id?>" <?php echo (@$_REQUEST['campId']==$_id?' selected="selected"':'') ?>><?php echo $_camp['desc']?></option>
							<?php }?>
						</select>
					</div>
					<div class="col-lg-2">
						<button onclick="findSubmit()" type="button" class="btn btn-primary btn-lg">查找</button>
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- /.col-lg-12 -->
</div>


<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 列表 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>届数</th>
						<th>战斗编号</th>
						<th>阵营</th>
						<th>参赛成员</th>
					</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<?php echo \Phalcon\Tag::javascriptInclude("js/My97DatePicker/WdatePicker.js"); ?>
<script>
var gTable1;
$(document).ready(function(){
    gTable1 = $('#dataTable1').DataTable({
		"autoWidth": false,
		"processing": true,
        "serverSide": true,
        "ajax": {
            "url": "/admin/ajaxCitybattleCamp",
			"type": "POST",
            "data": function ( d ) {
				d.roundId = $("#cbRoundId").val();
				d.battleId = $("#cbBattleId").val();
				d.campId = $("#cbCampId").val();
            }
        },
		"columns": [
			{ "data": "round_id" },
			{ "data": "battle_id" },
			{ "data": "camp_id" },
			{ "data": "player" },
        ],
		"pageLength": 25
	});
});


function findSubmit(){
	gTable1.draw();
}
</script>