<style>
#dataTable1{
	background:white;
}
#dataTable1 th{
	width:150px;
}
#dataTable1 td{
	/*word-wrap:break-word;
	word-break:break-all;*/
}
#detailInfoModal .form-control{
	word-wrap:break-word;
	word-break:break-all;
	height:auto;
}

.Wdate{
	height:30px;
	width:250px;
}
#dataTable1_filter{
	display:none;
}
</style>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">公会详情</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>

<div class="row" id="orderFilterForm">
	<div class="col-lg-12">
		<div class="panel panel-danger">
			<div class="panel-heading"> 筛选 </div>
			<div class="panel-body">
				<form method="POST">
					<div class="form-group">
						<label>届数</label>
						<input class="form-control" id="crossRoundId" style="width:250px;" value="<?php echo @$_REQUEST['roundId']?>" defaultVal="">
					</div>
					<div class="form-group">
						<label>战斗编号</label>
						<input class="form-control" id="crossbattleId" style="width:250px;" value="<?php echo @$_REQUEST['battleId']?>" defaultVal="">
					</div>
					<div class="form-group">
						<label>服</label>
						<input class="form-control" id="crossServer" style="width:250px;" value="<?php echo @$_REQUEST['serverId']?>" defaultVal="">
					</div>
					<div class="form-group">
						<label>公会Id</label>
						<input class="form-control" id="crossGuild" style="width:250px;" value="<?php echo @$_REQUEST['guildId']?>" defaultVal="">
					</div>
					<div class="col-lg-2">
						<button onclick="findSubmit()" type="button" class="btn btn-primary btn-lg">查找</button>
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- /.col-lg-12 -->
</div>


<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 列表 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>届数</th>
						<th>战斗编号</th>
						<th>服务器</th>
						<th>公会id</th>
						<th>公会名称</th>
						<th>公会短名</th>
						<th>会长</th>
						<th>当前积分</th>
						<th>参赛成员</th>
					</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<?php echo \Phalcon\Tag::javascriptInclude("js/My97DatePicker/WdatePicker.js"); ?>
<script>
var gTable1;
$(document).ready(function(){
    gTable1 = $('#dataTable1').DataTable({
		"autoWidth": false,
		"processing": true,
        "serverSide": true,
        "ajax": {
            "url": "/admin/ajaxCrossGuild",
			"type": "POST",
            "data": function ( d ) {
				d.roundId = $("#crossRoundId").val();
				d.battleId = $("#crossbattleId").val();
				d.serverId = $("#crossServer").val();
				d.guildId = $("#crossGuild").val();
            }
        },
		"columns": [
			{ "data": "round_id" },
			{ "data": "battle_id" },
			{ "data": "server" },
			{ "data": "guild_id" },
			{ "data": "name" },
			{ "data": "short_name" },
			{ "data": "leader_player_nick" },
			{ "data": "score" },
			{ "data": "player" },
        ],
		"pageLength": 25
	});
});


function findSubmit(){
	gTable1.draw();
}
</script>