<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">建筑信息</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 操作 </div>
			<div class="panel-body">
				<button class="btn btn-warning btn-xs" type="button" onclick="restartDisp('')">重启所有</button>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 建筑 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>脚本名</th>
						<th>操作</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach($method as $_k => $_m){
						?>
					<tr>
						<td><?php echo $_k?></td>
						<td><button class="btn btn-warning btn-xs" type="button" onclick="restartDisp('<?php echo $_k?>')">重启</button></td>
					</tr>
					<?php }?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<!-- /.col-lg-12 -->
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 操作日志 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable2">
					<thead>
					<tr>
						<th>编号</th>
						<th>事件</th>
						<th>时间</th>
					</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>


<script>
$(document).ready(function(){
    $('#dataTable1').DataTable({
		"pageLength": 50
	});
	$('#dataTable2').DataTable({
		"processing": true,
        "serverSide": true,
        "ajax": {
            "url": "/admin/ajaxDispLog",
			"type": "POST",
            "data": function ( d ) {
            }
        },
		"columns": [
            { "data": "id" },
            { "data": "memo" },
            { "data": "create_time" }
        ],
		"pageLength": 25
	});
});

function restartDisp(method){
	send_request_json('/admin/ajaxDispOperation', 
		{method: method}, 
		function(ret){
		if(ret.err == 'ok'){
			alertOk('操作成功', function(){
				location.reload();
			});
		}else{
			alertErr(ret.err);
		}
	});
}
</script>