<style>
/*
#dataTable1 th{
	max-width:100px!important;
	width:100px!important;
}
#dataTable1 td{
	word-wrap:break-word;
	word-break:break-all;
}
*/
#dataTable2 th{
	width:150px;
}
</style>

<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">联盟信息</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>

<?php if(@$guild){?>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 联盟信息 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable2">
					<tbody>
					<tr>
						<th>联盟编号</th><td><?php echo $guild['id']?></td>
					</tr>
					<tr>
						<th>名称</th><td><?php echo $guild['name']?></td>
					</tr>
					<tr>
						<th>短名称</th><td><?php echo $guild['short_name']?></td>
					</tr>
					<tr>
						<th>盟主</th><td><a href="javascript:linkPlayer(1, <?php echo $guild['leader_player_id']?>, 1)"><?php echo $guild['leader_player_id']?>(<?php echo $guild['leader_player_name']?>)</a></td>
					</tr>
					<tr>
						<th>人数</th><td><?php echo $guild['num']?></td>
					</tr>
					<tr>
						<th>人数容量</th><td><?php echo $guild['max_num']?></td>
					</tr>
					<tr>
						<th>阵营</th><td><?php echo $campName?></td>
					</tr>
					<tr>
						<th>入盟确认</th><td><?php echo @[0=>'不需要', 1=>'需要'][$guild['need_check']]?></td>
					</tr>
					<tr>
						<th>战力</th><td><?php echo number_format($guild['guild_power'])?></td>
					</tr>
					<tr>
						<th>描述</th><td><?php echo $guild['desc']?></td>
					</tr>
					<tr>
						<th>公告</th><td><?php echo $guild['notice']?></td>
					</tr>
					<tr>
						<th>入盟府衙等级</th><td><?php echo $guild['condition_fuya_level']?></td>
					</tr>
					<tr>
						<th>入盟战力</th><td><?php echo number_format($guild['condition_player_power'])?></td>
					</tr>
					<tr>
						<th>商店荣誉</th><td><?php echo number_format($guild['coin'])?></td>
					</tr>
					<tr>
						<th>士兵击杀数量</th><td><?php echo number_format($guild['kill_soldier_num'])?></td>
					</tr>
					<tr>
						<th>捐献积分</th><td><?php echo number_format($guild['mission_score'])?></td>
					</tr>
					<tr>
						<th>建盟时间</th><td><?php echo date('Y-m-d H:i:s', $guild['create_time'])?></td>
					</tr>
					<tr>
						<th>成员</th><td><?php 
						foreach($members as $_k => $_v){?>
							<a href="javascript:linkPlayer(1, <?php echo $_v['player_id']?>, 1)">[R<?php echo $_v['rank']?>]<?php echo $_v['Player']['nick']?>(<?php echo $_v['player_id']?>)</a><br>
						<?php }?>
						</td>
					</tr>
					<tr>
						<th>联盟建筑</th><td><?php 
						foreach($builds as $_v){?>
							<?php echo $_v['name']?>(x:<?php echo $_v['x']?>, y:<?php echo $_v['y']?>)<?php echo $_v['status']?> <br>
						<?php }?>
						</td>
					</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<?php }?>


<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 联盟列表 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>联盟编号</th>
						<th>名称</th>
						<th>短名称</th>
						<th>盟主</th>
						<th>人数</th>
						<th>人数容量</th>
						<!--<th>入盟确认</th>
						<th>战力</th>
						<th>描述</th>
						<th>公告</th>
						<th>入盟府衙等级</th>
						<th>入盟战力</th>
						<th>商店荣誉</th>
						<th>士兵击杀数量</th>
						<th>捐献积分</th>
						<th>建盟时间</th>
						<th>成员</th>-->
						<th>查看详情</th>
					</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>


<script>
$(document).ready(function(){
    $('#dataTable1').DataTable({
		"autoWidth": false,
		"processing": true,
        "serverSide": true,
        "ajax": {
            "url": "/admin/ajaxGuildInfo",
			"type": "POST",
            "data": function ( d ) {
            }
        },
		"columns": [
            { "data": "id" },
            { "data": "name" },
			{ "data": "short_name" },
			{ "data": "leader_player_id" },
			{ "data": "num" },
			{ "data": "max_num" },
			/*{ "data": "need_check" },
			{ "data": "guild_power" },
			{ "data": "desc" },
			{ "data": "notice" },
			{ "data": "condition_fuya_level" },
			{ "data": "condition_player_power" },
			{ "data": "coin" },
			{ "data": "kill_soldier_num" },
			{ "data": "mission_score" },
            { "data": "create_time" },
			{ "data": "members" },*/
			{ "data": "button" },
        ],
		"pageLength": 25
	});
	//$("#dataTable1_filter input[type=search]").attr('title', '（）中内容不支持搜索');
});

function showGuildDetail(guildId){
	location.href = '/admin/guildInfo?guildId='+guildId;
}
</script>