<style>
#dataTable1 pre{
	background-color:transparent;
	border:transparent;
}
#dataTable1{
	background:#ffffff;
}
</style>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">管理端日志</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>

<div class="row">
	<div class="col-lg-4">
		<div class="panel panel-default">
			<div class="panel-heading"> 查询条件 </div>
			<div class="panel-body">
				<form action="/admin/sendAllMail" method="POST">
					<div class="form-group" id="block_usercode">
						<label>管理员</label>
						<select class="form-control" id="logAdminName">
							<option value="0">---所有---</option>
						<?php foreach($adminUser as $_user){?>
							<option value="<?php echo $_user['name']?>"><?php echo $_user['name']?></option>
						<?php }?>
						</select>
					</div>
					<div class="form-group">
						<label>日志类型</label>
						<select class="form-control" id="logAdminType">
						<option value="0">---所有---</option>
						<?php foreach($authType as $_authCode => $_type){?>
							<option value="<?php echo $_authCode?>"><?php echo $_type?></option>
						<?php }?>
						</select>
					</div>
					<button type="button" class="btn btn-primary" onclick="findSubmit()">查询</button>
				</form>
			</div>
		</div>
	</div>
	<!-- /.col-lg-12 -->
</div>


<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 管理端日志 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>编号</th>
						<th>管理员</th>
						<th>类型</th>
						<th>内容</th>
						<th>时间</th>
					</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>


<script>
var gTable1;
$(document).ready(function(){
    gTable1 = $('#dataTable1').DataTable({
		"processing": true,
        "serverSide": true,
        "ajax": {
            "url": "/admin/ajaxLogAdmin",
			"type": "POST",
            "data": function ( d ) {
				d.adminName = $("#logAdminName").val();
				d.adminType = $("#logAdminType").val();
            }
        },
		"columns": [
            { "data": "id" },
			{ "data": "name" },
			{ "data": "type" },
            { "data": "memo" },
            { "data": "create_time" }
        ],
		"pageLength": 25,
		"order": [[0, 'desc']]
	});
	//$("#dataTable1_filter input[type=search]").attr('title', '（）中内容不支持搜索');
	$("#dataTable1").on('click', '.extrainfoBlk', function(){
		if($(this).find('pre').length > 0){
			$(this).find('.extrainfo').html($(this).find('pre').html());
		}else{
			$(this).find('.extrainfo').wrapInner('<pre></pre>');
		}
	});
});

function findSubmit(){
	gTable1.draw();
}
</script>