<style>
#dataTable1 pre{
	background-color:transparent;
	border:transparent;
}

#dataTable1_filter{
	display:none;
}
.Wdate{
	height:30px;
	width:250px;
}
#dataTable1{
	background:#ffffff;
}
</style>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">监控假量</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
  
<div class="row" id="orderFilterForm">
	<div class="col-lg-6">
		<div class="panel panel-danger">
			<div class="panel-heading"> 筛选 </div>
			<div class="panel-body">

				<!-- <div id="block_begintime" class="form-group">
					<label>开始时间</label>
					<input id="beginTime" placeholder="" class="form-control Wdate" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})" defaultVal=""/>
				</div>
				<div id="block_endtime" class="form-group">
					<label>结束时间</label>
					<input id="endTime" placeholder="" class="form-control Wdate" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})" defaultVal=""/>
				</div>-->
				<div id="block_begintime" class="form-group">
					<label>平均在线时间</label>
					<select id="condition_online" placeholder="整数"  defaultVal="1" />
						<option value="1">大于</option>
						<option value="2">小于</option>
					</select>
					<input id="onlineTime" placeholder="分钟"  onfocus="" defaultVal="5"/>
				</div>
			    <div id="block_begintime" class="form-group">
					<label>平均主公获取经验</label>
					<select id="condition_exp" placeholder="整数"  defaultVal="1" />
						<option value="1">大于</option>
						<option value="2">小于</option>
					</select>
					<input id="exp" placeholder="整数"  onfocus="" defaultVal="1"/>
				</div>
				<div id="block_begintime" class="form-group">
					<label>主公等级</label>
					<select id="condition_level" placeholder="整数"  defaultVal="1" />
						<option value="1">大于</option>
						<option value="2">小于</option>
					</select>
					<input id="level" placeholder="整数"  onfocus="" defaultVal="1"/>
				</div>
				<div id="block_begintime" class="form-group">
					<label>注册登录天数</label>
					<select id="condition_reg" placeholder="整数" defaultVal="1" />
						<option value="1">大于</option>
						<option value="2">小于</option>
					</select>
					<input id="regDays" placeholder="整数"  onfocus="" defaultVal="1"/>
				</div>

				
				<div class="col-lg-2">
					<button onclick="findSubmit()" type="button" class="btn btn-primary btn-lg">筛选</button>
				</div>
				<div class="col-lg-2">
					<button onclick="resetForm()" type="button" class="btn btn-warning btn-lg">清空</button>
				</div>
		
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 监控假量 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>playerId</th>
						<th>渠道</th>
						<th>平均在线时长(分钟)</th>
						<th>平均经验</th>
						<th>等级</th>
						<th>注册登录天数</th>
					</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<?php echo \Phalcon\Tag::javascriptInclude("js/My97DatePicker/WdatePicker.js"); ?>
<script>
var gTable1;
$(document).ready(function(){
    gTable1 = $('#dataTable1').DataTable({
		"processing": true,
        "serverSide": true,
        "ajax": {
            "url": "/admin/ajaxLogPlayerOnline",
			"type": "POST",
            "data": function ( d ) {
                //d.playerId = $("#log_playerId").val();
				//d.beginTime = $("#beginTime").val();
				//d.endTime = $("#endTime").val();
				d.onlineTime = $("#onlineTime").val();
				d.condition_online = $("#condition_online").val();
				d.exp = $("#exp").val();
				d.condition_exp = $("#condition_exp").val();
				d.level = $("#level").val();
				d.condition_level = $("#condition_level").val();
				d.regDays = $("#regDays").val();
				d.condition_reg = $("#condition_reg").val();
				
            }
        },
		"columns": [
			{ "data": "player_id" },
			{ "data": "channel" },
			{ "data": "avgline" },
			{ "data": "avgexp" },
			{ "data": "level" },
			{ "data": "reglogin" },
        ],
		"pageLength": 25
	});
	$("#dataTable1_filter input[type=search]").attr('title', '（）中内容不支持搜索');
	
	$("#dataTable1").on('click', '.extrainfoBlk', function(){
		if($(this).find('pre').length > 0){
			$(this).find('.extrainfo').html($(this).find('pre').html());
		}else{
			$(this).find('.extrainfo').wrapInner('<pre></pre>');
		}
	});
});

function resetForm(){
	$("#orderFilterForm").find('input,select,textarea').each(function(){
		$(this).val($(this).attr('defaultVal'));
	});
}

function findSubmit(){
	gTable1.draw();
}
</script>