<style>
.checkbox-list * {font-weight: 100 !important;}
</style>
<?php echo \Phalcon\Tag::javascriptInclude("js/My97DatePicker/WdatePicker.js"); ?>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">跨服武斗服务器配置</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
<?php if(isset($_GET['show'])):?>
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="form-group">
						<label style="font-size:20px;font-family:bold;">名称：</label><input style="width:200px;" id="name">
					</div>
					<label style="font-size:20px;font-family:bold;">勾选所选服务器</label>
					<div class="form-group checkbox-list">
						<?php
						$serverList = (new ServerList)->dicGetAll();
						$pkGroup = (new PkGroup)->getAllGroup();
						foreach($serverList as $v):
							foreach($pkGroup as $vv) {
								if(in_array($v['id'], $vv['server_ids'])) {
									continue 2;
								}
							}
						?>
						<label><input type="checkbox" name="serverList" value="<?=$v['id']?>" /><?=$v['areaName'].'|'.$v['name']?></label>&nbsp;&nbsp;&nbsp;&nbsp;
						<?php
						endforeach;
						?>
						<br><br>
						本赛季开始时间：<input class="Wdate" type="text" id="currentRoundStartTime" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd',onpicked:afterPick,minDate:'<?=date('Y-m-d')?>'})"/> <?=PkGroup::START_TIME?>
						<br><br>
						下赛季开始时间：<input type="text" id="nextRoundStartTime" readonly="true"/> <?=PkGroup::START_TIME?>
					</div>
					<div class="form-group">
						<button type="button" onclick="G.doAdd()" style="margin-right:50px;">保存</button>
						<button type="button" onclick="G.cancel()">取消</button>
					</div>
				</div>
			</div>
		</div>
	</div>
<?php else: ?>
<button onclick="G.add();">新 增</button>
<?php endif;?>
<div class="row" style="margin-top:20px;">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="chatTable">
					<thead>
					<tr>
						<th>编号</th>
						<th>名称</th>
						<th>关联服务器</th>
						<th>赛季开始时间</th>
						<th>赛季实际结束时间</th>
						<th>赛季下一轮开始时间</th>
						<th>操作</th>
						<th>操作记录</th>
					</tr>
					</thead>
					<tbody>
					<?php
					$serverList = (new ServerList)->dicGetAll();
					$serverList = Set::combine($serverList, '{n}.id', '{n}.areaName');
					$pkGroup    = (new PkGroup)->getAllGroup();
					foreach($pkGroup as $k=>$v):
						?>
						<tr>
							<td><?=$v['id']?></td>
							<td>
								<?=$v['name']?>
							</td>
							<td>
								<?php
								$sname = [];
								foreach($v['server_ids'] as $sid) {
									$sname[] = $serverList[$sid];
								}
								echo implode(",", $sname);
								?>
							</td>
							<td>
								<?=$v['current_round_start_time']?>
							</td>
							<td>
								<?=date('Y-m-d H:i:s', strtotime($v['next_round_start_time'])-2*60*60)?>
							</td>
							<td>
								<?=$v['next_round_start_time']?>
							</td>
							<td>
								<button class="btn btn-success btn-xs" type="button" onclick="G.modify(<?=$v['id']?>);">编辑</button>
								<button class="btn btn-danger btn-xs" type="button" onclick="G.close(<?=$v['id']?>);">关闭</button>
							</td>
							<td style="width:300px;">
								<?=$v['update_log']?>
							</td>
						</tr>
					<?php endforeach;?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<script>
	//数字时间戳转换成日期时间函数，time为传入的数字时间戳，如果数字时间戳先前作了/1000运算，请先*1000再传入
	function changeTimeFormat(time) {
		var date = new Date(time);
		var month = date.getMonth() + 1 < 10 ? "0" + (date.getMonth() + 1) : date.getMonth() + 1;
		var currentDate = date.getDate() < 10 ? "0" + date.getDate() : date.getDate();
		var hh = date.getHours() < 10 ? "0" + date.getHours() : date.getHours();
		var mm = date.getMinutes() < 10 ? "0" + date.getMinutes() : date.getMinutes();
		return date.getFullYear() + "-" + month + "-" + currentDate;
		//返回格式：yyyy-MM-dd hh:mm
	}
	function afterPick(){
		var currentRoundStartTime = $('#currentRoundStartTime').val();
		var nextRoundStartTime = Date.parse(currentRoundStartTime+' 00:00:00')+10*24*60*60*1000;
		$('#nextRoundStartTime').val(changeTimeFormat(nextRoundStartTime));
		return;
	}
	var G = {};
	G.add = function (){
		linkPage('admin/pkConfig', {"show":1});
	};
	G.doAdd = function(){
		var name = $('#name').val();
		if(!$.trim(name)) {
			alert('请输入名称');
			$('#name').focus();
			return;
		}
		var serverIds = [];
		$('input:checkbox').each(function(k, v){
			if(v.checked) {
				serverIds.push(v.value)
			}
		});
		if(serverIds.length<1){
			alert('请选择服务器');
			return;
		}
		var currentRoundStartTime = $('#currentRoundStartTime').val();
		var nextRoundStartTime = $('#nextRoundStartTime').val();
		if(!currentRoundStartTime) alert('选择赛季开始日期');
		if(!nextRoundStartTime) alert('选择下一赛季开始日期（即本赛季结束时间）');
		$.post('/admin/ajaxPkConfig/', {"serverId":serverIds, "name":name, "currentRoundStartTime":currentRoundStartTime, "nextRoundStartTime":nextRoundStartTime}, function(o){
			alertOk('添加成功', flushPage);
		});
	};
	G.modify = function(id){
		linkPage('admin/pkConfigModify', {"id":id});
	};
	G.close = function(id){
		$.post('/admin/ajaxPkConfigModify/', {"id":id, "close":1}, function(o){
			var o = $.trim(o);
			if(o=='time') {
				alertErr('赛季未结束');
			}
			else if(o=='ok') {
				alertOk('删除成功', flushPage);
			}
			else if(o=='fail') {
				alertErr('删除失败');
			}
		});
	}
	G.cancel = function (){
		linkPage('admin/pkConfig');
	};
	function flushPage(){
		G.cancel();
	}
	(function(){
		$('#name').focus();
	})();
</script>