<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">天赋信息</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 天赋 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>名称</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach($ps as $_ps){
						?>
					<tr>
						<td><?php echo $talent[$_ps['talent_id']]['desc1'].'Lv'.$talent[$_ps['talent_id']]['level_id'].'('.$_ps['talent_id'].')'?></td>
					</tr>
					<?php }?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<!-- /.col-lg-12 -->
</div>


<script>
$(document).ready(function(){
    $('#dataTable1').DataTable({
		"pageLength": 50
	});
});
</script>