<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">背包信息</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>

<div class="row">
	<div class="col-lg-4">
		<div class="panel panel-primary">
			<div class="panel-heading"> 背包道具 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>名称</th>
						<th>数量</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach($pi as $_pi){?>
					<tr>
						<td><?php echo $item[$_pi['item_id']]['desc1']?>(<?php echo $_pi['item_id']?>)</td>
						<td><?php echo $_pi['num']?></td>
					</tr>
					<?php }?>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<div class="col-lg-4">
		<div class="panel panel-success">
			<div class="panel-heading"> 主公道具 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable2">
					<thead>
					<tr>
						<th>名称</th>
						<th>是否装备</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach($pem as $_pem){?>
					<tr>
						<td><?php echo $equipMaster[$_pem['equip_master_id']]['desc1']?>(<?php echo $_pem['equip_master_id']?>)</td>
						<td><?php echo [0=>'否', 1=>'是'][$_pem['status']]?></td>
					</tr>
					<?php }?>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<div class="col-lg-4">
		<div class="panel panel-warning">
			<div class="panel-heading"> 武将道具 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable3">
					<thead>
					<tr>
						<th>名称</th>
						<th>数量</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach($pe as $_k => $_pe){?>
					<tr>
						<td><?php echo $equipment[$_k]['desc1']?>(<?php echo $_k?>)</td>
						<td><?php echo $_pe?></td>
					</tr>
					<?php }?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<script>
$(document).ready(function(){
    $('#dataTable1,#dataTable2,#dataTable3').DataTable({
		//"pageLength": 50
	});
	
	$(".dataTables_info").parent().removeClass('col-sm-6').addClass('col-sm-4');
	$(".dataTables_paginate").parent().removeClass('col-sm-6').addClass('col-sm-8');
});
</script>