<style>
#dataTable1{
	background:white;
}
#dataTable1 th{
	width:150px;
}
#dataTable1 td{
	/*word-wrap:break-word;
	word-break:break-all;*/
}
#detailInfoModal .form-control{
	word-wrap:break-word;
	word-break:break-all;
	height:auto;
}

#dataTable1 th:nth-child(4),#dataTable1 td:nth-child(4),
#dataTable1 th:nth-child(5),#dataTable1 td:nth-child(5),
#dataTable1 th:nth-child(8),#dataTable1 td:nth-child(8),
#dataTable1 th:nth-child(9),#dataTable1 td:nth-child(9),
#dataTable1 th:nth-child(11),#dataTable1 td:nth-child(11),
#dataTable1 th:nth-child(12),#dataTable1 td:nth-child(12),
#dataTable1 th:nth-child(13),#dataTable1 td:nth-child(13),
#dataTable1 th:nth-child(14),#dataTable1 td:nth-child(14){
	display:none;
}
.Wdate{
	height:30px;
	width:250px;
}
</style>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">玩家邮件</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>

<div class="row" id="orderFilterForm">
	<div class="col-lg-6">
		<div class="panel panel-danger">
			<div class="panel-heading"> 筛选 </div>
			<div class="panel-body">
				<div id="block_begintime" class="form-group">
					<label>开始时间</label>
					<input id="beginTime" placeholder="" class="form-control Wdate" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})" defaultVal=""/>
				</div>
				<div id="block_endtime" class="form-group">
					<label>结束时间</label>
					<input id="endTime" placeholder="" class="form-control Wdate" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})" defaultVal=""/>
				</div>
				<div id="block_type" class="form-group">
					<label>类型</label>
					<select class="form-control" id="mailType" style="width:250px;" defaultVal="0">
						<option value="0">所有</option>
						<?php foreach($types as $_k => $_t){?>
						<option value="<?php echo $_k?>"><?php echo $_t?></option>
						<?php }?>
					</select>
				</div>
				<div id="block_status" class="form-group">
					<label>状态</label>
					<select class="form-control" id="mailStatus" style="width:250px;" defaultVal="">
						<option value="">所有</option>
						<option value="0">普通</option>
						<option value="1">收藏</option>
						<option value="-1">删除</option>
					</select>
				</div>
				<div class="col-lg-2">
					<button onclick="findSubmit()" type="button" class="btn btn-primary btn-lg">筛选</button>
				</div>
				<div class="col-lg-2">
					<button onclick="resetForm()" type="button" class="btn btn-warning btn-lg">清空</button>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 玩家邮件 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>编号</th>
						<th>玩家id</th>
						<th>类型</th>
						<th>发信id</th>
						<th>邮件内容id</th>
						<th>发信者</th>
						<th>标题</th>
						<th>阅读标记<br><font color="green">0:未读，1:已读，2:附件已领</font></th>
						<th>备注</th>
						<th>状态<br><font color="green">0:普通，1:收藏，-1:删除</font></th>
						<th>内容</th>
						<th>数据</th>
						<th>道具</th>
						<th>过期时间</th>
						<th>时间</th>
						<th>操作</th>
					</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<!-- 邮件详情 -->
<div class="modal fade" id="detailInfoModal" tabindex="-1" role="dialog" aria-labelledby="detailInfoModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="detailInfoModalLabel">邮件详情</h4>
			</div>
			<div class="modal-body">
				<!--<div class="form-group">
					<label class="control-label">编号:</label>
					<div class="form-control">
						
					</div>
					<div style="clear:both"></div>
				</div>-->
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
			</div>
		</div>
	</div>
</div>


<?php echo \Phalcon\Tag::javascriptInclude("js/My97DatePicker/WdatePicker.js"); ?>
<script>
var gTable1;
$(document).ready(function(){
    gTable1 = $('#dataTable1').DataTable({
		"autoWidth": false,
		"processing": true,
        "serverSide": true,
        "ajax": {
            "url": "/admin/ajaxPlayerMail",
			"type": "POST",
            "data": function ( d ) {
                d.playerId = "<?php echo $playerId?>";
				d.beginTime = $("#beginTime").val();
				d.endTime = $("#endTime").val();
				d.type = $("#mailType").val();
				d.status = $("#mailStatus").val();
            }
        },
		"columns": [
            { "data": "id" },
            { "data": "player_id" },
            { "data": "type" },
            { "data": "connect_id" },
            { "data": "mail_info_id" },
			{ "data": "from_player", "orderable": false },
			{ "data": "title", "orderable": false },
			{ "data": "read_flag" },
			{ "data": "memo" },
			{ "data": "status" },
			{ "data": "msg" },
			{ "data": "data" },
			{ "data": "item" },
			{ "data": "expire_time" },
            { "data": "create_time" },
			{ "data": "operation", "orderable": false}
        ],
		"pageLength": 25
	});
	$("#dataTable1_filter input[type=search]").attr('title', '（）中内容不支持搜索');
});

function resetForm(){
	$("#orderFilterForm").find('input,select,textarea').each(function(){
		$(this).val($(this).attr('defaultVal'));
	});
}

function findSubmit(){
	gTable1.draw();
}

function showGroup(id){
	$(".chatGroup_"+id).toggle();
}

function showDetail(obj){
	var tr = $(obj).closest('tr');
	$("#detailInfoModal .modal-body *").remove();
	var str = [];
	$("#dataTable1 th").each(function(i){
		str.push('<div class="form-group">\
					<label class="control-label">'+$(this).html()+':</label>\
					<div class="form-control">'+tr.find('td:eq('+i+')').html()+'</div>\
					<div style="clear:both"></div>\
				</div>');
	});
	$("#detailInfoModal .modal-body").append(str.join(''));
	$("#detailInfoModal").modal();
}

function changeStatus(playerId, id, status){
	if(status == -1){
		var str = '删除'
	}else{
		var str = '恢复'
	}
	if(confirm('是否'+str+'邮件？')){
		send_request_json('/admin/ajaxPlayerMailChangeStatus', 
			{playerId: playerId, id: id, status: status}, 
			function(ret){
			if(ret.err == 'ok'){
				alertOk(str+'成功', function(){
					location.reload();
				});
			}else{
				alertErr(ret.err);
			}
		});
	}
}
</script>