<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">发送礼包</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 渠道 </div>
			<div class="panel-body">
				选择渠道
				<select id="playerdoSendGiftChannel" onchange="changeChannel()">
					<?php foreach($channels as $_c){?>
						<option value="<?php echo $_c?>" <?php echo ($_c == $channel ? 'selected=selected':'')?>><?php echo $_c?></option>
					<?php }?>
				</select>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 礼包列表 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>id</th>
						<th>名称</th>
						<th>价格</th>
						<th>activity_id</th>
						<th>series</th>
						<th>series_order</th>
						<th>gift_type</th>
						<th>联盟礼包</th>
						<th>操作</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach($gift as $_g){
						?>
					<tr>
						<td><?php echo $_g['id']?></td>
						<td><?php echo $_g['language']?></td>
						<td><?php echo $_g['price']?></td>
						<td><?php echo $_g['activity_id']?></td>
						<td><?php echo $_g['series']?></td>
						<td><?php echo $_g['series_order']?></td>
						<td><?php echo $_g['gift_type']?></td>
						<td><?php echo ($_g['guild_drop_id'] ? '有':'无')?></td>
						<td><button class="btn btn-warning btn-xs" type="button" onclick="sendActivityGift(<?php echo $_g['id']?>, '<?php echo $_g['language']?>')">发送</button></td>
					</tr>
					<?php }?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<!-- /.col-lg-12 -->
</div>

<script>
$(document).ready(function(){
    $('#dataTable1').DataTable({
		"pageLength": 200
	});
});

function changeChannel(){
	var channel = $("#playerdoSendGiftChannel").val();
	linkPage('admin/playerdoSendGift', {channel: channel});
}

function sendActivityGift(id, name){
	var playerId = '<?php echo $playerId?>';
	var channel = $("#playerdoSendGiftChannel").val();
	if(confirm('是否给玩家['+playerId+']发送礼包“'+name+'”')){
		send_request_json('/admin/ajaxPlayerdoSendGift', 
			{'playerId': playerId, 'id': id, channel: channel}, 
			function(ret){
			if(ret.err == 'ok'){
				alertOk('发送成功', function(){
					location.reload();
				});
			}else{
				alertErr(ret.err);
			}
		});
	}
}
</script>