<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">科技信息</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 科技 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>名称</th>
						<th>状态</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach($ps as $_ps){
						?>
					<tr>
						<td><?php echo ($_ps['science_id'] ? $science[$_ps['science_id']]['desc1'].'Lv'.$science[$_ps['science_id']]['level_id'].'('.$_ps['science_id'].')' : '')?>
						<?php if($_ps['status']){?>
							=><?php echo ($_ps['next_id'] ? $science[$_ps['next_id']]['desc1'].'Lv'.$science[$_ps['next_id']]['level_id'].'('.$_ps['next_id'].')' : '')?>
						<?php }?>
						</td>
						<td><?php echo [0=>'正常', 1=>'研究中'][$_ps['status']]?></td>
					</tr>
					<?php }?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<!-- /.col-lg-12 -->
</div>


<script>
$(document).ready(function(){
    $('#dataTable1').DataTable({
		"pageLength": 50
	});
});
</script>