<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">增益信息</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 增益 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>名称</th>
						<th>值</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach($pbt as $_k => $_pbt){
						if(!@$buffn[$_k]) continue;?>
					<tr>
						<td><?php echo $buffn[$_k]['desc1']?>(<?php echo $_k?>)</td>
						<td <?php echo ($_pbt ? 'class="text-success"' : '')?>>+<?php echo $_pbt?><?php echo ($buffn[$_k]['buff_type']==1 ? '%':'')?></td>
					</tr>
					<?php }?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<!-- /.col-lg-12 -->
</div>

<script>
$(document).ready(function(){
    $('#dataTable1').DataTable({
		"pageLength": 50
	});
	
});
</script>
