<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">公告列表</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
<div class="panel-heading">GM服务器时间:<?=date('Y-m-d H:i:s')?></div>

<span id="notice"></span>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"> 世界聊天 </div>
			<div class="panel-body">
				<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
					<thead>
					<tr>
						<th>顺序</th>
                        <th>标题</th>
                        <th>内容</th>
                        <th>最新</th>
                        <th>开始时间</th>
                        <th>结束时间</th>
                        <th>渠道</th>
						<th>操作</th>
					</tr>
					</thead>
					<tbody>
                    <?php 
                    $j = 1;
                    foreach($data as $k=>$v):?>
                        <tr>
                            <td><?=$j++?></td>
                            <td width="150px"><?=$v['title']?></td>
                            <td><?=$v['content']?></td>
                            <td><?=$v['is_new']==1?'新':''?></td>
                            <td><?=$v['begin_time']?></td>
                            <td><?=$v['end_time']?></td>
                            <td><?=$v['channel']?></td>
                            <td>
                            <a class="btn btn-danger" href="javascript:;" onclick="delNotice(<?=$v['id']?>);">删除</a>
                            <a class="btn btn-success" href="/admin/modifyNotice/<?=$v['id']?>">编辑</a>
                            <?php if($v['is_new']==0):?>
                            <a class="btn btn-info" href="javascript:;" onclick="setNew(<?=$v['id']?>);">标为最新</a>
                            <?php else:?>
                            <a class="btn btn-primary" href="javascript:;" onclick="setNotNew(<?=$v['id']?>);">标为非最新</a>
                            <?php endif;?>
                            </td>
                        </tr>
                    <?php endforeach;?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<script>
function delNotice(id){
    if(confirm('是否删除此条公告:id='+id)) {
        $.post('/admin/ajaxDeleteNotice', {"id":id}, function(o) {
            alert(o);
            location.reload();
        });
    }
}
function setNew(id){
    $.post('/admin/ajaxSetNoticeNew', {"id":id}, function(o){
        location.reload();
    });
}
function setNotNew(id){
    $.post('/admin/ajaxSetNoticeNotNew', {"id":id}, function(o){
        location.reload();
    });
}

$(document).ready(function(){
	$('#dataTable1').DataTable({
		"pageLength": 100,
		"aaSorting": [[ 4, "desc" ]]
	});
});
</script>