-- INSERT UPDATE sql for 'King_rank_reward';
INSERT INTO `King_rank_reward` (`id`,`min_rank`,`max_rank`,`bonus`) VALUES ('1','1','1','471001') ON DUPLICATE KEY UPDATE `id` = '1',`min_rank` = '1',`max_rank` = '1',`bonus` = '471001';
INSERT INTO `King_rank_reward` (`id`,`min_rank`,`max_rank`,`bonus`) VALUES ('2','2','2','471002') ON DUPLICATE KEY UPDATE `id` = '2',`min_rank` = '2',`max_rank` = '2',`bonus` = '471002';
INSERT INTO `King_rank_reward` (`id`,`min_rank`,`max_rank`,`bonus`) VALUES ('3','3','3','471003') ON DUPLICATE KEY UPDATE `id` = '3',`min_rank` = '3',`max_rank` = '3',`bonus` = '471003';
INSERT INTO `King_rank_reward` (`id`,`min_rank`,`max_rank`,`bonus`) VALUES ('4','4','4','471004') ON DUPLICATE KEY UPDATE `id` = '4',`min_rank` = '4',`max_rank` = '4',`bonus` = '471004';
INSERT INTO `King_rank_reward` (`id`,`min_rank`,`max_rank`,`bonus`) VALUES ('5','5','5','471005') ON DUPLICATE KEY UPDATE `id` = '5',`min_rank` = '5',`max_rank` = '5',`bonus` = '471005';
INSERT INTO `King_rank_reward` (`id`,`min_rank`,`max_rank`,`bonus`) VALUES ('6','6','6','471006') ON DUPLICATE KEY UPDATE `id` = '6',`min_rank` = '6',`max_rank` = '6',`bonus` = '471006';
INSERT INTO `King_rank_reward` (`id`,`min_rank`,`max_rank`,`bonus`) VALUES ('7','7','7','471007') ON DUPLICATE KEY UPDATE `id` = '7',`min_rank` = '7',`max_rank` = '7',`bonus` = '471007';
INSERT INTO `King_rank_reward` (`id`,`min_rank`,`max_rank`,`bonus`) VALUES ('8','8','8','471008') ON DUPLICATE KEY UPDATE `id` = '8',`min_rank` = '8',`max_rank` = '8',`bonus` = '471008';
INSERT INTO `King_rank_reward` (`id`,`min_rank`,`max_rank`,`bonus`) VALUES ('9','9','9','471009') ON DUPLICATE KEY UPDATE `id` = '9',`min_rank` = '9',`max_rank` = '9',`bonus` = '471009';
INSERT INTO `King_rank_reward` (`id`,`min_rank`,`max_rank`,`bonus`) VALUES ('10','10','9999','471010') ON DUPLICATE KEY UPDATE `id` = '10',`min_rank` = '10',`max_rank` = '9999',`bonus` = '471010';
