-- INSERT UPDATE sql for 'Vip';
INSERT INTO `Vip` (`id`,`vip_level`,`vip_exp`) VALUES ('1','1','0') ON DUPLICATE KEY UPDATE `id` = '1',`vip_level` = '1',`vip_exp` = '0';
INSERT INTO `Vip` (`id`,`vip_level`,`vip_exp`) VALUES ('2','2','100') ON DUPLICATE KEY UPDATE `id` = '2',`vip_level` = '2',`vip_exp` = '100';
INSERT INTO `Vip` (`id`,`vip_level`,`vip_exp`) VALUES ('3','3','300') ON DUPLICATE KEY UPDATE `id` = '3',`vip_level` = '3',`vip_exp` = '300';
INSERT INTO `Vip` (`id`,`vip_level`,`vip_exp`) VALUES ('4','4','500') ON DUPLICATE KEY UPDATE `id` = '4',`vip_level` = '4',`vip_exp` = '500';
INSERT INTO `Vip` (`id`,`vip_level`,`vip_exp`) VALUES ('5','5','500') ON DUPLICATE KEY UPDATE `id` = '5',`vip_level` = '5',`vip_exp` = '500';
INSERT INTO `Vip` (`id`,`vip_level`,`vip_exp`) VALUES ('6','6','1100') ON DUPLICATE KEY UPDATE `id` = '6',`vip_level` = '6',`vip_exp` = '1100';
INSERT INTO `Vip` (`id`,`vip_level`,`vip_exp`) VALUES ('7','7','1200') ON DUPLICATE KEY UPDATE `id` = '7',`vip_level` = '7',`vip_exp` = '1200';
INSERT INTO `Vip` (`id`,`vip_level`,`vip_exp`) VALUES ('8','8','2400') ON DUPLICATE KEY UPDATE `id` = '8',`vip_level` = '8',`vip_exp` = '2400';
INSERT INTO `Vip` (`id`,`vip_level`,`vip_exp`) VALUES ('9','9','5000') ON DUPLICATE KEY UPDATE `id` = '9',`vip_level` = '9',`vip_exp` = '5000';
INSERT INTO `Vip` (`id`,`vip_level`,`vip_exp`) VALUES ('10','10','10000') ON DUPLICATE KEY UPDATE `id` = '10',`vip_level` = '10',`vip_exp` = '10000';
INSERT INTO `Vip` (`id`,`vip_level`,`vip_exp`) VALUES ('11','11','22500') ON DUPLICATE KEY UPDATE `id` = '11',`vip_level` = '11',`vip_exp` = '22500';
INSERT INTO `Vip` (`id`,`vip_level`,`vip_exp`) VALUES ('12','12','36000') ON DUPLICATE KEY UPDATE `id` = '12',`vip_level` = '12',`vip_exp` = '36000';
