<style>
.playerdoItemCartNum{
	width:20px;
	background:#777;
	border:0;
	text-align:center;
}
.playerdoItemCartNum:hover,
.playerdoItemCartNum:focus{
	background:#999;
}
.cartItem{
	margin-right:10px;
}
.alert-green{
	background-color: #5cb85c;
    border-color: #5cb85c;
    color: #fff;
}
.alert-red{
    background-color: #d9534f;
    border-color: #d9534f;
    color: #fff;
}
#playerdoItemCart .popover-content{
	color:#121212;
}
</style>
<div id="itemDropCreater">
	<hr>
	<h1 id="itemDropCreateTitle">道具代码生成器</h1>
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-danger">
				<div class="panel-heading"> 购物车 
					<button class="btn btn-primary btn-xs" type="button" onclick="getDropCode(<?php echo @$callback?>)"><i aria-hidden="true" class="fa fa-arrow-circle-up"></i> 生成道具代码</button>
					<button class="btn btn-warning btn-xs" type="button" onclick="resetCart()"><i aria-hidden="true" class="fa fa-trash"></i> 清空</button>
				</div>
				<div class="panel-body" id="playerdoItemCart">
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-4 blockDropResource">
			<div class="panel panel-green">
				<div class="panel-heading"> 基础资源 </div>
				<div class="panel-body">
					<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
						<thead>
						<tr>
							<th>id</th>
							<th>名称</th>
							<th>操作</th>
						</tr>
						</thead>
						<tbody>
						<?php foreach($resource as $_resource){	?>
						<tr>
							<td><?php echo $_resource['id']?></td>
							<td><?php echo $_resource['name']?></td>
							<td><button class="btn btn-success btn-xs" type="button" onclick="addtoCart(1, <?php echo $_resource['id']?>, '<?php echo $_resource['name']?>')">增加</button></td>
						</tr>
						<?php }?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="col-lg-4 blockDropResource2" style="display:none">
			<div class="panel panel-green">
				<div class="panel-heading"> 基础资源 </div>
				<div class="panel-body">
					<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable1">
						<thead>
						<tr>
							<th>id</th>
							<th>名称</th>
							<th>操作</th>
						</tr>
						</thead>
						<tbody>
						<?php foreach($resource as $_resource){	
						if(!$_resource['consume']) continue;?>
						<tr>
							<td><?php echo $_resource['id']?></td>
							<td><?php echo $_resource['name']?></td>
							<td><button class="btn btn-success btn-xs" type="button" onclick="addtoCart(1, <?php echo $_resource['id']?>, '<?php echo $_resource['name']?>')">增加</button></td>
						</tr>
						<?php }?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="col-lg-4 blockDropSoldier">
			<div class="panel panel-red">
				<div class="panel-heading"> 士兵 </div>
				<div class="panel-body">
					<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable2">
						<thead>
						<tr>
							<th>id</th>
							<th>名称</th>
							<th>操作</th>
						</tr>
						</thead>
						<tbody>
						<?php foreach($soldier as $_soldier){	?>
						<tr>
							<td><?php echo $_soldier['id']?></td>
							<td><?php echo $_soldier['desc1']?></td>
							<td><button class="btn btn-success btn-xs" type="button" onclick="addtoCart(8, <?php echo $_soldier['id']?>, '<?php echo $_soldier['desc1']?>')">增加</button></td>
						</tr>
						<?php }?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="clearfix"></div>
		<div class="col-lg-4 blockDropItem">
			<div class="panel panel-info">
				<div class="panel-heading"> 背包道具 </div>
				<div class="panel-body">
					<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable3">
						<thead>
						<tr>
							<th>id</th>
							<th>名称</th>
							<th>操作</th>
						</tr>
						</thead>
						<tbody>
						<?php foreach($item as $_item){
							if($_item['item_type'] == 1) continue;
							?>
						<tr>
							<td><?php echo $_item['id']?></td>
							<td><?php echo $_item['desc1']?></td>
							<td><button class="btn btn-success btn-xs" type="button" onclick="addtoCart(2, <?php echo $_item['id']?>, '<?php echo $_item['desc1']?>')">增加</button></td>
						</tr>
						<?php }?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		
		<div class="col-lg-4 blockDropMasterItem">
			<div class="panel panel-success">
				<div class="panel-heading"> 主公道具 </div>
				<div class="panel-body">
					<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable4">
						<thead>
						<tr>
							<th>id</th>
							<th>名称</th>
							<th>操作</th>
						</tr>
						</thead>
						<tbody>
						<?php foreach($equipMaster as $_equipMaster){?>
						<tr>
							<td><?php echo $_equipMaster['id']?></td>
							<td><?php echo $_equipMaster['desc1']?></td>
							<td><button class="btn btn-success btn-xs" type="button" onclick="addtoCart(7, <?php echo $_equipMaster['id']?>, '<?php echo $_equipMaster['desc1']?>')">增加</button></td>
						</tr>
						<?php }?>
						</tbody>
					</table>
				</div>
			</div>
		</div>

		<div class="col-lg-4 blockDropEquipment">
			<div class="panel panel-warning">
				<div class="panel-heading"> 武将道具 </div>
				<div class="panel-body">
					<table width="100%" class="table table-striped table-bordered table-hover" id="dataTable5">
						<thead>
						<tr>
							<th>id</th>
							<th>名称</th>
							<th>操作</th>
						</tr>
						</thead>
						<tbody>
						<?php foreach($equipment as $_equipment){
							if(!in_array($_equipment['equip_type'], [0, 2, 3, 4])){
								continue;
							}
							$name = $_equipment['desc1'] . 'Lv' . $_equipment['star_level'];
							?>
						<tr>
							<td><?php echo $_equipment['id']?></td>
							<td><?php echo $name?></td>
							<td><button class="btn btn-success btn-xs" type="button" onclick="addtoCart(4, <?php echo $_equipment['id']?>, '<?php echo $name?>')">增加</button></td>
						</tr>
						<?php }?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>


<script>
$(document).ready(function(){
	$('#dataTable1,#dataTable2,#dataTable3,#dataTable4,#dataTable5').DataTable({
		//"pageLength": 50
		"columnDefs": [
			{ "orderable": false, "targets": 2 }
		]
	});
	
	$(".dataTables_info").parent().removeClass('col-sm-6').addClass('col-sm-4');
	$(".dataTables_paginate").parent().removeClass('col-sm-6').addClass('col-sm-8');
	$("#playerdoItemCart").on('blur keyup', '.playerdoItemCartNum', function(){
		var v = $(this).val().replace(/\D/g,'')*1;
		if(v < 1){
			v = 1;
		}
		var len = v.toString().length;
		$(this).css({'width': len*10+'px'});
		$(this).val(v);
	}).trigger('blur');
	
	
});

var gClickFlag = true;
function addtoCart(type, itemId, itemName, num){
	if(!gClickFlag)
		return;
	gClickFlag = false;
	if(isnull(num)){
		num = 1;
	}else{
		num *= 1;
	}
	var color = {1: 'green', 2: 'info', 7: 'success', 4: 'warning', 8: 'red'};
	var d = $(".cartItem[cartItemId='"+type+','+itemId+"']");
	if(d.length > 0){
		d.find(".playerdoItemCartNum").val(d.find(".playerdoItemCartNum").val()*1+num);
	}else{
		$("#playerdoItemCart").append('<div role="alert" class="col-lg-2 cartItem alert alert-'+color[type]+' alert-dismissible fade in" cartItemId="'+type+','+itemId+'">\
				<button aria-label="Close" data-dismiss="alert" class="close" type="button"><span aria-hidden="true">×</span></button>\
				<span class="n">'+itemName+'('+itemId+')'+'</span> \
				<span class="badge"><input class="playerdoItemCartNum" type="text" value="'+num+'"/></span>\
			</div>');
	}
	if($(".cartItem").length == 1){
		showEditableTip();
	}
	gClickFlag = true;
}

function resetCart(){
	if(!gClickFlag)
		return;
	gClickFlag = false;
	if(confirm('是否清空购物车')){
		$("#playerdoItemCart *").remove();
	}
	gClickFlag = true;
}

function getDropCode(cb){
	//组合道具
	var item = [];
	var memo = [];
	$(".cartItem").each(function(){
		item.push($(this).attr('cartItemId')+','+$(this).find('.playerdoItemCartNum').val());
		memo.push($(this).find('.n').text()+'x'+$(this).find('.playerdoItemCartNum').val());
	});
	<?php if(@$dropInputId){?>
	item = item.join(';');
	$("#<?php echo $dropInputId?>").val(item);
	<?php }?>
	<?php if(@$memoInputId){?>
	memo = memo.join("\r\n");
	$("#<?php echo $memoInputId?>").val(memo);
	<?php }?>
	runfunc(cb);
}

var showEditableTipFlag = true;
function showEditableTip(){
	if(!showEditableTipFlag)
		return false;
	showEditableTipFlag = false;
	$('.playerdoItemCartNum:first').popover({
		trigger: 'focus',
		content: '点击编辑',
		placement: 'top',
		animation: true,
		delay: 1000,
	}).popover('show');
	setTimeout(function(){
		$('.playerdoItemCartNum:first').popover('hide');
	}, 2000);
}

function generateBeautyFromStr(str){
	$("#playerdoItemCart *").remove();
	showLoading();
	send_request_json('/admin/ajaxTransDropstr', 
	{
		dropstr: str
	}, 
	function(ret){
		if(ret.err == 'ok'){
			$.each(ret.data, function(i, n){
				addtoCart(n.type_id, n.id, n.name, n.num);
			});
			hideLoading();
		}else{
			alertErr(ret.err);
			hideLoading();
		}
	});
}

function switchToConsume(){
	$(".blockDropResource").hide();
	$(".blockDropResource2").show();
	$(".blockDropMasterItem").hide();
}

function switchToDrop(){
	$(".blockDropResource").show();
	$(".blockDropResource2").hide();
	$(".blockDropMasterItem").show();
}
</script>