TRUNCATE `Country_science_exp`;
INSERT INTO `Country_science_exp` (`id`,`week_number`,`autoexp_per_hour`,`player_exp_rate`) VALUES ('1','1','2500','10000');
INSERT INTO `Country_science_exp` (`id`,`week_number`,`autoexp_per_hour`,`player_exp_rate`) VALUES ('2','2','3000','13000');
INSERT INTO `Country_science_exp` (`id`,`week_number`,`autoexp_per_hour`,`player_exp_rate`) VALUES ('3','3','3600','16900');
INSERT INTO `Country_science_exp` (`id`,`week_number`,`autoexp_per_hour`,`player_exp_rate`) VALUES ('4','4','4300','21900');
INSERT INTO `Country_science_exp` (`id`,`week_number`,`autoexp_per_hour`,`player_exp_rate`) VALUES ('5','5','5100','28400');
INSERT INTO `Country_science_exp` (`id`,`week_number`,`autoexp_per_hour`,`player_exp_rate`) VALUES ('6','6','6100','36900');
INSERT INTO `Country_science_exp` (`id`,`week_number`,`autoexp_per_hour`,`player_exp_rate`) VALUES ('7','7','7300','47900');
INSERT INTO `Country_science_exp` (`id`,`week_number`,`autoexp_per_hour`,`player_exp_rate`) VALUES ('8','8','8700','62200');
INSERT INTO `Country_science_exp` (`id`,`week_number`,`autoexp_per_hour`,`player_exp_rate`) VALUES ('9','9','10400','80800');
INSERT INTO `Country_science_exp` (`id`,`week_number`,`autoexp_per_hour`,`player_exp_rate`) VALUES ('10','10','12400','105000');
INSERT INTO `Country_science_exp` (`id`,`week_number`,`autoexp_per_hour`,`player_exp_rate`) VALUES ('11','11','14800','136500');
INSERT INTO `Country_science_exp` (`id`,`week_number`,`autoexp_per_hour`,`player_exp_rate`) VALUES ('12','12','17700','177400');
