TRUNCATE `Faq_Guide`;
INSERT INTO `Faq_Guide` (`id`,`name_id`,`name`,`desc_id`,`desc`,`redirect_type`,`button_name_id`,`castle_lv`) VALUES ('1','332001','城池建筑','333001','','','','');
INSERT INTO `Faq_Guide` (`id`,`name_id`,`name`,`desc_id`,`desc`,`redirect_type`,`button_name_id`,`castle_lv`) VALUES ('2','332002','资源','333002','','','','');
INSERT INTO `Faq_Guide` (`id`,`name_id`,`name`,`desc_id`,`desc`,`redirect_type`,`button_name_id`,`castle_lv`) VALUES ('3','332003','武将','333003','','','','');
INSERT INTO `Faq_Guide` (`id`,`name_id`,`name`,`desc_id`,`desc`,`redirect_type`,`button_name_id`,`castle_lv`) VALUES ('4','332004','装备','333004','','','','');
INSERT INTO `Faq_Guide` (`id`,`name_id`,`name`,`desc_id`,`desc`,`redirect_type`,`button_name_id`,`castle_lv`) VALUES ('5','332005','PVE','333005','','','','');
INSERT INTO `Faq_Guide` (`id`,`name_id`,`name`,`desc_id`,`desc`,`redirect_type`,`button_name_id`,`castle_lv`) VALUES ('6','332006','PVP','333006','','','','');
INSERT INTO `Faq_Guide` (`id`,`name_id`,`name`,`desc_id`,`desc`,`redirect_type`,`button_name_id`,`castle_lv`) VALUES ('7','332007','主公天赋','333007','','','','');
INSERT INTO `Faq_Guide` (`id`,`name_id`,`name`,`desc_id`,`desc`,`redirect_type`,`button_name_id`,`castle_lv`) VALUES ('8','332008','军团','333008','','','','');
INSERT INTO `Faq_Guide` (`id`,`name_id`,`name`,`desc_id`,`desc`,`redirect_type`,`button_name_id`,`castle_lv`) VALUES ('9','332009','联盟','333009','','','','');
INSERT INTO `Faq_Guide` (`id`,`name_id`,`name`,`desc_id`,`desc`,`redirect_type`,`button_name_id`,`castle_lv`) VALUES ('10','332010','VIP','333010','','','','');
INSERT INTO `Faq_Guide` (`id`,`name_id`,`name`,`desc_id`,`desc`,`redirect_type`,`button_name_id`,`castle_lv`) VALUES ('11','332011','活动','333011','','','','');
INSERT INTO `Faq_Guide` (`id`,`name_id`,`name`,`desc_id`,`desc`,`redirect_type`,`button_name_id`,`castle_lv`) VALUES ('12','332012','神武将','333012','','','','');
