TRUNCATE `General_recruit`;
INSERT INTO `General_recruit` (`id`,`desc1`) VALUES ('100101','吕布');
INSERT INTO `General_recruit` (`id`,`desc1`) VALUES ('100201','关羽');
INSERT INTO `General_recruit` (`id`,`desc1`) VALUES ('100301','张飞');
INSERT INTO `General_recruit` (`id`,`desc1`) VALUES ('100401','刘备');
INSERT INTO `General_recruit` (`id`,`desc1`) VALUES ('100501','赵云');
INSERT INTO `General_recruit` (`id`,`desc1`) VALUES ('100601','马超');
INSERT INTO `General_recruit` (`id`,`desc1`) VALUES ('100701','诸葛亮');
INSERT INTO `General_recruit` (`id`,`desc1`) VALUES ('100801','司马懿');
INSERT INTO `General_recruit` (`id`,`desc1`) VALUES ('100901','周瑜');
INSERT INTO `General_recruit` (`id`,`desc1`) VALUES ('101001','黄忠');
