TRUNCATE `Pay_way`;
INSERT INTO `Pay_way` (`id`,`channel`,`pay_way`,`pay_way_lv`) VALUES ('1','googleplay','googleplay,paypal,mycard','1,5,5');
INSERT INTO `Pay_way` (`id`,`channel`,`pay_way`,`pay_way_lv`) VALUES ('2','appstore','appstore','1');
INSERT INTO `Pay_way` (`id`,`channel`,`pay_way`,`pay_way_lv`) VALUES ('3','dsuc','paypal,alipay,mycard','1,1,1');
INSERT INTO `Pay_way` (`id`,`channel`,`pay_way`,`pay_way_lv`) VALUES ('4','googlestore','googlestore,paypal,mycard','1,5,5');
INSERT INTO `Pay_way` (`id`,`channel`,`pay_way`,`pay_way_lv`) VALUES ('5','appstore_tw','appstore_tw','1');
INSERT INTO `Pay_way` (`id`,`channel`,`pay_way`,`pay_way_lv`) VALUES ('6','anysdk','lenovo,oppo,gionee,meizu,vivo,mi,coolpad,tencent,baidu,qihu,test_anysdk,pengyouwan,downjoy,muzhiwan,x7sy,6y','1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1');
INSERT INTO `Pay_way` (`id`,`channel`,`pay_way`,`pay_way_lv`) VALUES ('7','huawei','huawei','1');
INSERT INTO `Pay_way` (`id`,`channel`,`pay_way`,`pay_way_lv`) VALUES ('8','aligames','aligames','1');
INSERT INTO `Pay_way` (`id`,`channel`,`pay_way`,`pay_way_lv`) VALUES ('9','dsuc_cn','alipay_cn','1');
INSERT INTO `Pay_way` (`id`,`channel`,`pay_way`,`pay_way_lv`) VALUES ('10','appstore_cn','appstore_cn','1');
INSERT INTO `Pay_way` (`id`,`channel`,`pay_way`,`pay_way_lv`) VALUES ('11','taptap','alipay_cn','1');
