TRUNCATE `SkillAnims`;
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3100001','WD_Skill_FeiJian_Ballistic','4','2','弹道_孙权技能');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3100002','WD_Skill_QuanYiZhiJi_Dst','2','1','受击_孙权技能');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3100003','WD_Skill_QiXi_Dst','2','1','突袭_张辽技能');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3100004','WD_Skill_HeiFengHou_Dst','2','1','黑风吼_张飞技能');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3100005','WD_Skill_SongWei_Dst','2','1','颂威_曹丕技能');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3100006','WD_Skill_QingLongZhan_Dst','2','1','青龙斩_关羽技能');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3100007','WD_Skill_QuanYiZhiJi_Dst','2','1','权宜之计_孙权技能');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3200001','WD_Skill_QingLongZhan_Srt','1','2','青龙斩_关羽发动');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3200002','WD_Skill_SongWei_Srt','1','1','颂威_曹丕发动');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3200003','WD_Skill_KuRou_Srt','1','1','苦肉_黄盖发动');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3200004','WD_Skill_HeiFengHou_Srt','1','1','黑风吼_张飞发动');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3200005','WD_Skill_BaWangNu_Srt','1','1','霸王怒_孙策发动');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3200006','WD_Skill_JianXiong_Srt','1','1','奸雄_曹操发动');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3199901','WD_Skill_DaoBingjineng_Dst','2','1','通用刀');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3199902','WD_Skill_ChangMaoBingjineng_Dst','2','1','通用长矛');
INSERT INTO `SkillAnims` (`id`,`path`,`play_type`,`anims_type`,`desc`) VALUES ('3199903','WD_Skill_GongBingjineng_Dst','2','1','通用弓');
