-- INSERT UPDATE sql for 'Warfare_service_config';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('1','open_time','20:00:00','跨服战开始时间
时间显示方式
08:00:00') ON DUPLICATE KEY UPDATE `id` = '1',`name` = 'open_time',`data` = '20:00:00',`text` = '跨服战开始时间
时间显示方式
08:00:00';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('2','ready_time','3','战斗准备时间
分钟
') ON DUPLICATE KEY UPDATE `id` = '2',`name` = 'ready_time',`data` = '3',`text` = '战斗准备时间
分钟
';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('3','fight_time','30','战斗最长时间
分钟') ON DUPLICATE KEY UPDATE `id` = '3',`name` = 'fight_time',`data` = '30',`text` = '战斗最长时间
分钟';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('4','wf_gate1_hitpoint','floor(20000+$lv*400)','城门1血量，根据守方玩家总府衙等级计算') ON DUPLICATE KEY UPDATE `id` = '4',`name` = 'wf_gate1_hitpoint',`data` = 'floor(20000+$lv*400)',`text` = '城门1血量，根据守方玩家总府衙等级计算';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('5','wf_gate2_hitpoint','floor(15000+$lv*300)','城门2血量，根据守方玩家总府衙等级计算') ON DUPLICATE KEY UPDATE `id` = '5',`name` = 'wf_gate2_hitpoint',`data` = 'floor(15000+$lv*300)',`text` = '城门2血量，根据守方玩家总府衙等级计算';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('6','wf_gate3_hitpoint','floor(10000+$lv*200)','城门3血量，根据守方玩家总府衙等级计算') ON DUPLICATE KEY UPDATE `id` = '6',`name` = 'wf_gate3_hitpoint',`data` = 'floor(10000+$lv*200)',`text` = '城门3血量，根据守方玩家总府衙等级计算';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('7','wf_playercastle_hitpoint','2000+$lv*200','玩家城防值，根据玩家府衙等级计算') ON DUPLICATE KEY UPDATE `id` = '7',`name` = 'wf_playercastle_hitpoint',`data` = '2000+$lv*200',`text` = '玩家城防值，根据玩家府衙等级计算';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('8','wf_catapult_atkpower','floor(3000+pow($power,0.5)*3)','投石车攻击力，根据驻守部队战力计算，') ON DUPLICATE KEY UPDATE `id` = '8',`name` = 'wf_catapult_atkpower',`data` = 'floor(3000+pow($power,0.5)*3)',`text` = '投石车攻击力，根据驻守部队战力计算，';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('9','wf_catapult_atkcolddown','30','投石车攻击cd时间') ON DUPLICATE KEY UPDATE `id` = '9',`name` = 'wf_catapult_atkcolddown',`data` = '30',`text` = '投石车攻击cd时间';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('10','wf_warhammer_hitpoint','floor(2000+$lv*40)','攻城锤血量，根据攻击方玩家总府衙等级计算') ON DUPLICATE KEY UPDATE `id` = '10',`name` = 'wf_warhammer_hitpoint',`data` = 'floor(2000+$lv*40)',`text` = '攻城锤血量，根据攻击方玩家总府衙等级计算';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('11','wf_warhammer_atkpower','floor(1000+pow($power,0.7)*2)','攻城锤攻击力，根据驻守部队总战力计算') ON DUPLICATE KEY UPDATE `id` = '11',`name` = 'wf_warhammer_atkpower',`data` = 'floor(1000+pow($power,0.7)*2)',`text` = '攻城锤攻击力，根据驻守部队总战力计算';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('12','wf_warhammer_atkcolddown','30','攻城锤攻击cd时间') ON DUPLICATE KEY UPDATE `id` = '12',`name` = 'wf_warhammer_atkcolddown',`data` = '30',`text` = '攻城锤攻击cd时间';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('13','wf_glaivethrower_atkpower','floor(1500+pow($power,0.5)*2)','床弩攻击力，根据驻守部队战力计算') ON DUPLICATE KEY UPDATE `id` = '13',`name` = 'wf_glaivethrower_atkpower',`data` = 'floor(1500+pow($power,0.5)*2)',`text` = '床弩攻击力，根据驻守部队战力计算';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('14','wf_glaivethrower_atkcolddown','30','床弩攻击cd时间') ON DUPLICATE KEY UPDATE `id` = '14',`name` = 'wf_glaivethrower_atkcolddown',`data` = '30',`text` = '床弩攻击cd时间';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('15','wf_ladder_hitpoint','floor(1000+$lv*20)','云梯血量，根据攻击方玩家总府衙等级计算') ON DUPLICATE KEY UPDATE `id` = '15',`name` = 'wf_ladder_hitpoint',`data` = 'floor(1000+$lv*20)',`text` = '云梯血量，根据攻击方玩家总府衙等级计算';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('16','wf_ladder_max_progress','10000','云梯进度最大值') ON DUPLICATE KEY UPDATE `id` = '16',`name` = 'wf_ladder_max_progress',`data` = '10000',`text` = '云梯进度最大值';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('17','wf_ladder_progress','floor(10+pow($power,0.5)/100)','云梯进度增量，根据驻守部队总战力计算') ON DUPLICATE KEY UPDATE `id` = '17',`name` = 'wf_ladder_progress',`data` = 'floor(10+pow($power,0.5)/100)',`text` = '云梯进度增量，根据驻守部队总战力计算';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('18','wf_ladder_progress_colddown','30','云梯进度增加cd时间') ON DUPLICATE KEY UPDATE `id` = '18',`name` = 'wf_ladder_progress_colddown',`data` = '30',`text` = '云梯进度增加cd时间';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('19','wf_ladder_respawn_time','60','云梯重生时间(秒)') ON DUPLICATE KEY UPDATE `id` = '19',`name` = 'wf_ladder_respawn_time',`data` = '60',`text` = '云梯重生时间(秒)';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('20','wf_basecastle_hitpoint','floor(10000+$lv*200)','防守方大本营血量，根据守方玩家总府衙等级计算') ON DUPLICATE KEY UPDATE `id` = '20',`name` = 'wf_basecastle_hitpoint',`data` = 'floor(10000+$lv*200)',`text` = '防守方大本营血量，根据守方玩家总府衙等级计算';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('21','wf_soldier_count_start','5000','初始士兵数量') ON DUPLICATE KEY UPDATE `id` = '21',`name` = 'wf_soldier_count_start',`data` = '5000',`text` = '初始士兵数量';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('22','wf_soldier_count_limit','5000','士兵数量上限(大于等于该上限后不能再购买士兵，玩家可以在4999的时候再次购买)') ON DUPLICATE KEY UPDATE `id` = '22',`name` = 'wf_soldier_count_limit',`data` = '5000',`text` = '士兵数量上限(大于等于该上限后不能再购买士兵，玩家可以在4999的时候再次购买)';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('23','wf_legion_count_limit','2','军团数量上限') ON DUPLICATE KEY UPDATE `id` = '23',`name` = 'wf_legion_count_limit',`data` = '2',`text` = '军团数量上限';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('24','wf_march_speed_buff','50000','行军速度buff，万分比') ON DUPLICATE KEY UPDATE `id` = '24',`name` = 'wf_march_speed_buff',`data` = '50000',`text` = '行军速度buff，万分比';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('25','wf_defender_respawn_time','30','防守方城池复活时间(秒)') ON DUPLICATE KEY UPDATE `id` = '25',`name` = 'wf_defender_respawn_time',`data` = '30',`text` = '防守方城池复活时间(秒)';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('26','wf_playercastle_respawn_price','10','城池立即复活消耗(元宝)') ON DUPLICATE KEY UPDATE `id` = '26',`name` = 'wf_playercastle_respawn_price',`data` = '10',`text` = '城池立即复活消耗(元宝)';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('27','wf_playercastle_respawn_soldier_count','5000','城池复活后获得的初始士兵数量') ON DUPLICATE KEY UPDATE `id` = '27',`name` = 'wf_playercastle_respawn_soldier_count',`data` = '5000',`text` = '城池复活后获得的初始士兵数量';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('28','wf_reinforcement_soldier_count','1000','购买士兵数量') ON DUPLICATE KEY UPDATE `id` = '28',`name` = 'wf_reinforcement_soldier_count',`data` = '1000',`text` = '购买士兵数量';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('29','wf_reinforcement_soldier_price','19','购买士兵价格(个人荣誉)costid') ON DUPLICATE KEY UPDATE `id` = '29',`name` = 'wf_reinforcement_soldier_price',`data` = '19',`text` = '购买士兵价格(个人荣誉)costid';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('30','wf_castle_teleport_colddown','120','城战迁城cd时间') ON DUPLICATE KEY UPDATE `id` = '30',`name` = 'wf_castle_teleport_colddown',`data` = '120',`text` = '城战迁城cd时间';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('31','wf_march_speed_burst','100','城战行军加速50%的价格') ON DUPLICATE KEY UPDATE `id` = '31',`name` = 'wf_march_speed_burst',`data` = '100',`text` = '城战行军加速50%的价格';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('32','wf_winner_reward','620001','参与者获胜奖') ON DUPLICATE KEY UPDATE `id` = '32',`name` = 'wf_winner_reward',`data` = '620001',`text` = '参与者获胜奖';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('33','wf_loser_reward','620002','参与者失败奖') ON DUPLICATE KEY UPDATE `id` = '33',`name` = 'wf_loser_reward',`data` = '620002',`text` = '参与者失败奖';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('34','wf_guild_winner_reward','620003','全盟大锅饭(胜者)') ON DUPLICATE KEY UPDATE `id` = '34',`name` = 'wf_guild_winner_reward',`data` = '620003',`text` = '全盟大锅饭(胜者)';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('35','team_join_num','10','一个联盟可以进入的最大城池数量') ON DUPLICATE KEY UPDATE `id` = '35',`name` = 'team_join_num',`data` = '10',`text` = '一个联盟可以进入的最大城池数量';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('36','wf_warhammer_respawn_time','60','攻城锤重生时间(秒)') ON DUPLICATE KEY UPDATE `id` = '36',`name` = 'wf_warhammer_respawn_time',`data` = '60',`text` = '攻城锤重生时间(秒)';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('37','all_soldier','50001','万能士兵ID') ON DUPLICATE KEY UPDATE `id` = '37',`name` = 'all_soldier',`data` = '50001',`text` = '万能士兵ID';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('38','wf_atkcastle_hitpointlost','floor(1000+pow($power,0.7)/3)','攻击玩家城堡战斗获胜后的城防损失(根据进攻玩家获胜后剩余战力计算)') ON DUPLICATE KEY UPDATE `id` = '38',`name` = 'wf_atkcastle_hitpointlost',`data` = 'floor(1000+pow($power,0.7)/3)',`text` = '攻击玩家城堡战斗获胜后的城防损失(根据进攻玩家获胜后剩余战力计算)';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('39','wf_atkgate_hitpointlost','floor(1000+pow($power,0.5)*4)','玩家攻击城门后的城防损失(根据进攻玩家战力计算)') ON DUPLICATE KEY UPDATE `id` = '39',`name` = 'wf_atkgate_hitpointlost',`data` = 'floor(1000+pow($power,0.5)*4)',`text` = '玩家攻击城门后的城防损失(根据进攻玩家战力计算)';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('40','wf_atkbasecastle_hitpointlost','floor(1000+pow($power,0.5)*4)','玩家攻击大本营后的城防损失(根据进攻玩家战力计算)') ON DUPLICATE KEY UPDATE `id` = '40',`name` = 'wf_atkbasecastle_hitpointlost',`data` = 'floor(1000+pow($power,0.5)*4)',`text` = '玩家攻击大本营后的城防损失(根据进攻玩家战力计算)';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('41','wf_reinforcement_soldier_price_gem','20','购买士兵价格(元宝)costid') ON DUPLICATE KEY UPDATE `id` = '41',`name` = 'wf_reinforcement_soldier_price_gem',`data` = '20',`text` = '购买士兵价格(元宝)costid';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('42','wf_enroll_start','08:00:00','报名开始时间') ON DUPLICATE KEY UPDATE `id` = '42',`name` = 'wf_enroll_start',`data` = '08:00:00',`text` = '报名开始时间';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('43','wf_match_start','19:00:00','报名截止时间/匹配开始时间') ON DUPLICATE KEY UPDATE `id` = '43',`name` = 'wf_match_start',`data` = '19:00:00',`text` = '报名截止时间/匹配开始时间';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('44','wf_award_start','21:10:00','发奖时间') ON DUPLICATE KEY UPDATE `id` = '44',`name` = 'wf_award_start',`data` = '21:10:00',`text` = '发奖时间';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('45','wf_close_time','21:10:00','活动结束时间') ON DUPLICATE KEY UPDATE `id` = '45',`name` = 'wf_close_time',`data` = '21:10:00',`text` = '活动结束时间';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('46','wf_guild_loser_reward','620004','全盟大锅饭(败者)') ON DUPLICATE KEY UPDATE `id` = '46',`name` = 'wf_guild_loser_reward',`data` = '620004',`text` = '全盟大锅饭(败者)';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('47','wf_guild_city_level','20','联盟报名参赛的成员城池等级底线') ON DUPLICATE KEY UPDATE `id` = '47',`name` = 'wf_guild_city_level',`data` = '20',`text` = '联盟报名参赛的成员城池等级底线';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('48','wf_guild_num','10','联盟报名参赛的成员人数底线') ON DUPLICATE KEY UPDATE `id` = '48',`name` = 'wf_guild_num',`data` = '10',`text` = '联盟报名参赛的成员人数底线';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('49','wf_attacker_respawn_time','20','攻击方复活cd时间（秒）') ON DUPLICATE KEY UPDATE `id` = '49',`name` = 'wf_attacker_respawn_time',`data` = '20',`text` = '攻击方复活cd时间（秒）';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('50','wf_attacker_respawn_add_time','5','攻方复活递增时间（秒）') ON DUPLICATE KEY UPDATE `id` = '50',`name` = 'wf_attacker_respawn_add_time',`data` = '5',`text` = '攻方复活递增时间（秒）';
INSERT INTO `Warfare_service_config` (`id`,`name`,`data`,`text`) VALUES ('51','wf_defender_respawn_add_time','5','守方复活递增时间（秒）') ON DUPLICATE KEY UPDATE `id` = '51',`name` = 'wf_defender_respawn_add_time',`data` = '5',`text` = '守方复活递增时间（秒）';
